### ISSUE TITLE
Can't run applyPatches.py

### ISSUE THREAD

**Issue by wgaylord** [ProjectTestificate/Spigot-MCP#1]
applyPatches.py fails with:

> Downloading DiffUtils 1.0.0
> Traceback (most recent call last):
>  File "applyPatches.py", line 7, in <module>
>    import diffutils
>  File "C:\Users\bill\Documents\GitHub\Spigot-MCP\DiffUtils\diffutils__init__.py", line 17, in <module>
>    from .api import diff, patch, undo_patch, parse_unified_diff, generate_unified_diff
>  File "C:\Users\bill\Documents\GitHub\Spigot-MCP\DiffUtils\diffutils\api.py", line 17, in <module>
>    from diffutils import myers
> ImportError: cannot import name myers

**Comment by wgaylord** [comment]
In 

> Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 10:55:48) [MSC v.1600 32 bit (Intel)]
> on windows 10

**Comment by Techcable** [comment]
Install DiffUtils with

```
git clone git@github.com:Techcable/DiffUtils.git
python3 -m pip install -e DiffUtils
```

**Comment by wgaylord** [comment]
Okay that makes sense.
